title: TL;DR.HackerNews24
description: Read it 1000 years later bro.
theme: null
markdown: kramdown
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true

# Canonical Cloudflare Pages URL
baseurl: ""
url: "https://tldr-24.pages.dev"

# Permalink configuration for posts
permalink: /:year/:month/:day/:title/

# Google Analytics
google_analytics: G-NVV6SYBRDW

# Defaults for posts
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
